### ISSUE TITLE
Awk / line-ending problem

### ISSUE THREAD

**Issue by gvanem** [ShiftMediaProject/libgpg-error#4]
Many of the `.awk` scripts are sensitive to DOS line-endings.

If I do a `git clone` of this project with  `autocrlf = true` in my `%APPDATA%/.gitconfig`, the generated code becomes
junk. Not compilable. 

A fix for me was running `dos2unix` on all `src/*.h.in` files. 
And BTW, I used a Cygwin `awk` (or more precisely `gawk.exe`).

**Comment by Sibras** [comment]
Firstly the awk files should never be needed with this repo as everything that is needed to compile with Visual Studio is provided in the SMP folder. Anything outside of that is provided by the upstream project that this repo is forked from and thus is not  directly supported here.

Secondly, this is expected behavior as all the files are stored in the git repo using LF line ending. The files are written for unix systems that are all by default LF line endings. So if you have your git setup to convert everything to CRLF you will likely encounter issues (this goes for all files written on/for unix systems). This repo assumes that autocrlf is disabled as a result.
